- id: check-azure-bicep
  name: az bicep build
  language: script
  entry: az_bicep_build.ps1
  files: .*.bicep$

- id: check-azure-bicep-python
  name: az bicep build (python)
  language: python
  entry: entry_az_bicep_build
  files: .*.bicep$
  additional_dependencies: ['azure-cli']

- id: check-azure-bicep-format
  name: az bicep format
  language: script
  entry: az_bicep_format.ps1
  files: .*.bicep$

- id: check-azure-bicep-format-python
  name: az bicep format (python)
  language: python
  entry: entry_az_bicep_format
  files: .*.bicep$
  additional_dependencies: ['azure-cli']
