- id: check-azure-bicep
  name: az bicep build
  language: script
  entry: az_bicep_build.ps1
  files: .*.bicep$

- id: check-azure-bicep-python
  name: az bicep build (python)
  language: python
  entry: az_bicep_build_python.py
  files: .*.bicep$
  #additional_dependencies: ['azure-cli']

- id: check-azure-bicep-python2
  name: az bicep build (python)2
  language: python
  entry: entry_function
  files: .*.bicep$
  #additional_dependencies: ['azure-cli']

