repos:
  - repo: https://github.com/Azure4DevOps/check-azure-bicep
    rev: master
    hooks:
      - id: check-azure-bicep
      - id: check-azure-bicep-python

  # - repo: local
  #   hooks:
  #     - id: check-azure-bicep
  #       name: check-azure-bicep
  #       language: system
  #       #entry: powershell -File ./src/az_bicep_build.ps1
  #       entry: pwsh -File ./src/az_bicep_build.ps1
  #       pass_filenames: true
  #       files: .*.bicep$
