repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-executables-have-shebangs
  # - repo: https://github.com/Azure4DevOps/check-azure-bicep
  #   rev: v0.5.3
  #   hooks:
      # - id: check-azure-bicep
      # - id: check-azure-bicep-python
      # - id: check-azure-bicep-format
      # - id: check-azure-bicep-format-python

  # - repo: local
  #   hooks:
  #     - id: check-azure-bicep
  #       name: check-azure-bicep
  #       language: system
  #       #entry: powershell -File ./src/az_bicep_build.ps1
  #       entry: pwsh -File ./src/az_bicep_build.ps1
  #       pass_filenames: true
  #       files: .*.bicep$


  - repo: local
    hooks:
      - id: check-azure-bicep
        name: check-azure-bicep
        language: system
        entry: pwsh -File ./az_bicep_build.ps1
        pass_filenames: true
        files: .*\.bicep$
      - id: check-azure-bicep-format
        name: check-azure-bicep-format
        language: system
        entry: pwsh -File ./az_bicep_format.ps1
        pass_filenames: true
        files: .*\.bicep$