variables:
  system.debug: true

trigger:
- master
- develop
- release/*
- feature/*
- hotfix/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

jobs:
- job: AgentJobMain
  displayName: Agent job - Main
  steps:
  - bash: |
      if [ -f .pre-commit-config.yaml ]; then
        echo "##vso[task.setVariable variable=FILEEXISTS_PRECOMMIT]true"
      fi
    displayName: Check if .pre-commit-config.yaml exist
  - script: |
      pip install pre-commit
      pre-commit --version
      pre-commit run --all-files
    condition: eq(variables.FILEEXISTS_PRECOMMIT, 'true')
    displayName: Execture pre-commit
