variables:
  system.debug: true

trigger:
- master
- develop
- release/*
- feature/*
- hotfix/*

pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: AgentJobGitVersion
  displayName: Agent job - GitVersion
  steps:
  - task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
    displayName: gitversion/setup
    inputs:
      versionSpec: 5.x

  - task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
    displayName: gitversion/execute

- job: AgentJobMain
  displayName: Agent job - Main
  strategy:
    maxParallel: 99
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macOS-latest'
      windows:
        imageName: 'windows-latest'
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.x'
      addToPath: true
      architecture: 'x64'

  - bash: |
      if [ -f .pre-commit-config.yaml ]; then
        echo "##vso[task.setVariable variable=FILEEXISTS_PRECOMMIT]true"
      fi
    displayName: Check if .pre-commit-config.yaml exist
  - script: |
      az bicep install
    condition: eq(variables.imageName, 'macOS-latest')
    retryCountOnTaskFailure: 5
    displayName: Run az bicep install on macOS-latest on ADO
  - script: |
      pip install pre-commit
      pre-commit --version
      pre-commit run --all-files
    condition: eq(variables.FILEEXISTS_PRECOMMIT, 'true')
    displayName: Execture pre-commit
