---
# See ../DEPENDENCIES.md#workaround-for-other-dependencies
name: Dependabot hack
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-hack-workflow
jobs:
  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: "ubuntu-latest"
    steps:
      # Dockerfile:
      - uses: azure/bicep@v0.13.1
      - uses: azure/azure-cli@azure-cli-2.42.0
      - uses: pre-commit/pre-commit@v2.20.0
