---
# See ../DEPENDENCIES.md#workaround-for-other-dependencies
name: Dependabot hack
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-hack-workflow
  workflow_dispatch:

jobs:
  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: "ubuntu-latest"
    steps:
      # Dockerfile:
      - uses: azure/azure-cli@azure-cli-2.65.0
      - uses: azure/bicep@v0.31.92
      - uses: pre-commit/pre-commit@v4.0.1
      
